# Generated by Django 4.2 on 2025-03-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
        ),
    ]
